name: Python Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Python Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: 3.11

    - name: Cache venv
      uses: actions/cache@v3
      with:
        path: .venv
        key: ${{ runner.os }}-venv-3.11-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-venv-3.11-

    - name: Create and activate virtual environment
      run: |
        python -m venv .venv
        source .venv/bin/activate
        python -m pip install --upgrade pip

    - name: Install dependencies
      run: |
        source .venv/bin/activate
        pip install -r requirements.txt

    - name: Run tests with pytest and generate coverage report
      run: |
        source .venv/bin/activate
        pytest tests/ -v --cov=./ --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: true
